//
//  ClearDocSummary.swift
//  ClearDoc
//
//  Created by Christian Grise on 7/25/26.
//

import FoundationModels

/// A structured, plain-language breakdown of a piece of text, produced by
/// ``ClearDocAnalyzer/analyze(_:)`` via Foundation Models' Guided
/// Generation.
///
/// This is the schema the on-device model is constrained to populate —
/// rather than returning free text that would need to be hand-parsed,
/// `analyze(_:)` returns a value of this type directly, with every field
/// already validated against its declared type and any ``Guide``
/// constraints below.
///
/// - Note: Every stored property is generated by the model, regardless of
///   whether a consuming app displays it. Keeping this type limited to
///   only the fields actually needed avoids spending extra generation
///   time on content nobody will show.
@Generable(description: "Document summary and classification")
public struct ClearDocSummary {

    /// A short, descriptive title for the text that was analyzed.
    @Guide(description: "Title")
    public var title: String

    /// A plain-language rewrite of the source text's overall meaning,
    /// intended to be easier to read than the original.
    @Guide(description: "Plain language summary")
    public var plainLanguageSummary: String

    /// Between three and six short bullet points capturing the main
    /// takeaways from the source text.
    ///
    /// - Important: With very short or sparse source text, a model can be
    ///   tempted to invent additional points just to satisfy this count
    ///   constraint. Worth spot-checking output against the original text
    ///   for anything that looks fabricated rather than extracted.
    @Guide(description: "Key points", .count(3...6))
    public var keyPoints: [String]

    /// Specific words or phrases from the source text worth calling out
    /// separately — for example unfamiliar terminology or anything a
    /// reader might want to double-check.
    @Guide(description: "Flagged terms")
    public var flaggedTerms: [String]

    /// The kind of document the model determined this text to be, as one
    /// of the cases in ``ClearDocCategory``.
    @Guide(description: "The type of document being analyzed")
    public var category: ClearDocCategory
}
